api_platform:
    mapping:
        paths:
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

    exception_to_status:
        App\Exception\NoAvailabilityException: 400
        App\Exception\InvalidTimeException: 422
        App\Exception\NoTimesMatchException: 422
